---
title: "Causal Inference for Time Series (Heat and Mortality)"
author: "Lauren Mock"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(tidyverse)
library(webshot)
library(xtable)

```

```{r}
# load original data
all_unmatched <- read.csv("../data/intermediate/all_processed.csv")
# now filter out any days with undefined treatment
unmatched <- all_unmatched %>%
    filter(!is.na(is_treated))

# load matched data
matched <- read.csv("../data/intermediate/matched.csv")

# load inference results
res <- read.csv(file = "../results/inference_results.csv")

# switch order of cities
all_unmatched$city <- factor(all_unmatched$city, levels = c("pitt", "seat", "chic", "la", "ny"))
unmatched$city <- factor(unmatched$city, levels = c("pitt", "seat", "chic", "la", "ny"))
res$city <- factor(res$city, levels = c("pitt", "seat", "chic", "la", "ny"))
res <- res[c(4,5,1,2,3),]

# cities
cities <- c("Pittsburgh", "Seattle", "Chicago", "Los Angeles", "New York")
```

```{r}
# table with median summer tmax in each city

# switch order of cities

# get median summer temp in each city
med_temps <- all_unmatched %>%
  filter(month %in% c("Jun", "Jul", "Aug", "Sep")) %>%
  group_by(city) %>%
  summarise(`Median Tmax` = median(tmax, na.rm = TRUE))

# reformat
med_temps <- med_temps %>%
  as.matrix() %>%
  `row.names<-`(cities) %>%
  as.data.frame() %>%
  dplyr::select(-c(city))

# export latex table
print(xtable(med_temps, type = "latex"), file = "med_temps.tex")

```

```{r}
# table with number of treated/matched units in each city

# table for unmatched data
n_tab <- unmatched %>%
  group_by(city, is_treated) %>%
  summarise(n = n()) %>%
  spread(key = "is_treated", value = "n") %>%
  rename(n.control = `FALSE`,
         n.treated = `TRUE`) %>%
  as.data.frame()

# add column for matched data
n_tab$n.pair <- res$n/2

# reformat
n_tab <- n_tab[,c(3,1,2,4)]
n_tab <- n_tab %>%
  `row.names<-`(cities) %>%
  dplyr::select(-c(city))

# add row for % of treated units ("heat waves") that were had a control match
n_tab$pct_matched <- (100*(n_tab$n.pair/n_tab$n.treated)) %>% round(1)

# export latex table
print(xtable(n_tab, type = "latex"), file = "n_tab.tex")
```

```{r}
# table for matching criteria

# matched on:
matched_on <- c("Year", 
                "Week of the year",
                "Day of the week",
                "NO2 day before experiment", 
                "O3 day before experiment")
matched_by <- c("0", "3", "0", "5 \U00B5g/m3", "5 \U00B5g/m3")

matched_tab <- data.frame(Covariate = matched_on,
                          `Discrepancy Allowed` = matched_by)

row.names(matched_tab) <- NULL

# export latex table
print(xtable(matched_tab, type = "latex"), file = "matched_tab.tex", include.rownames = FALSE)

```


```{r}

# tables with all results (for appendix)

res$city <- cities

# remove unnecessary columns
res <- res %>%
  dplyr::select(-c(mean.control, mean.treated, 
                   var.control, var.treated, var.tau.unpaired,
                   var.bayes))

# round to 1 place
res <- as_tibble(res) %>% mutate_at(vars(3:7, 27:28), funs(round(., 1)))

# round to 3 places
res <- as_tibble(res) %>% mutate_at(vars(9:24, 31:32), funs(round(., 3)))

# round to 5 places
res <- as_tibble(res) %>% mutate_at(vars(25:26, 29:30), funs(round(., 5)))

# manually adjust p-value for NY ATE
res$p_value_ATE[5] <- "<0.00001"
res$adjusted_p_value_ATE[5] <- "<0.00001"

#----- unite columns with lower and upper CI -----#

res <- unite(res, "CI.tau.unpaired", 
             c("lower.CI.tau.unpaired", "upper.CI.tau.unpaired"), sep = ", ") %>%
  mutate(CI.tau.unpaired = paste0("[", CI.tau.unpaired, "]"))

res <- unite(res, "CI.tau.paired", 
             c("lower.CI.tau.paired", "upper.CI.tau.paired"), sep = ", ") %>%
  mutate(CI.tau.paired = paste0("[", CI.tau.paired, "]"))

res <- unite(res, "IRR.CI", 
             c("lower.CI", "upper.CI"), sep = ", ") %>%
  mutate(IRR.CI = paste0("[", IRR.CI, "]"))

res <- unite(res, "IRR.CI.pairs", 
             c("lower.CI.pairs", "upper.CI.pairs"), sep = ", ") %>%
  mutate(IRR.CI.pairs = paste0("[", IRR.CI.pairs, "]"))

res <- unite(res, "IRR.CI.covs", 
             c("lower.CI.covs", "upper.CI.covs"), sep = ", ") %>%
  mutate(IRR.CI.covs = paste0("[", IRR.CI.covs, "]"))
  
res <- unite(res, "IRR.CI.unmatch", 
             c("lower.CI.covs.unmatch", "upper.CI.covs.unmatch"), sep = ", ") %>%
  mutate(IRR.CI.unmatch = paste0("[", IRR.CI.unmatch, "]"))
  
res <- unite(res, "bayes.CI", 
             c("lower.CI.bayes", "upper.CI.bayes"), sep = ", ") %>%
  mutate(bayes.CI = paste0("[", bayes.CI, "]"))

res <- unite(res, "fisher.ATE.CI", 
             c("fisher_ATE_low", "fisher_ATE_high"), sep = ", ") %>%
  mutate(fisher.ATE.CI = paste0("[", fisher.ATE.CI, "]"))

res <- unite(res, "fisher.RR.CI", 
             c("fisher_RR_low", "fisher_RR_high"), sep = ", ") %>%
  mutate(fisher.RR.CI = paste0("[", fisher.RR.CI, "]"))

```

```{r}

#----- table for ATE -----#

# select columns on difference scale
ATE_tab <- res %>%
  dplyr::select(c(city, pop, tau, ate_adj, CI.tau.unpaired, CI.tau.paired, fisher.ATE.CI,
                  p_value_ATE, adjusted_p_value_ATE, est.bayes, bayes.CI))

# rename
ATE_tab <- ATE_tab %>%
  rename(Population = pop,
         `Est. ATE` = tau,
         `Est. ATE/100k people` = ate_adj,
         `95% CI (unpaired)` = CI.tau.unpaired,
         `95% CI (paired)` = CI.tau.paired,
         `95% Fiducial interval` = fisher.ATE.CI,
         `Fisher p-value`  = p_value_ATE,
         `Adj. Fisher p-value`  = adjusted_p_value_ATE,
         `Est. ATE (Bayesian)` = est.bayes,
         `Bayesian 95% CI` = bayes.CI)

ATE_tab <- ATE_tab %>%
  as.matrix() %>%
  `row.names<-`(cities) %>%
  as.data.frame() %>%
  dplyr::select(-c(city))

# now switch rows and columns
ATE_tab <- t(ATE_tab) |> as.data.frame()

# export latex table
print(xtable(ATE_tab, type = "latex"), file = "ATE_tab.tex")

```

```{r}

#----- table for ATE and pop-adjusted ATE  -----#

ATE_tab_pop <- ATE_tab |>
  dplyr::select(c(Population, `Est. ATE`, `Est. ATE/100k people`, `Adj. Fisher p-value`))

# export latex table
print(xtable(ATE_tab_pop, type = "latex"), file = "ATE_tab_pop.tex")
```



```{r}

#----- table for RR -----#

# select columns on difference scale
RR_tab <- res %>%
  dplyr::select(c(city, IRR, IRR.CI, IRR.pairs, IRR.CI.pairs, IRR.covs, IRR.CI.covs,
                  IRR.covs.unmatch, IRR.CI.unmatch, p_value_RR, adjusted_p_value_RR, fisher.RR.CI))

# rename
RR_tab <- RR_tab %>%
  rename(`RR M_unadj` = IRR,
        `RR M_unadj CI` = IRR.CI,
        `RR M_pairs` = IRR.pairs,
        `RR M_pairs CI` = IRR.CI.pairs,
        `RR M_covs` = IRR.covs,
        `RR M_covs CI` = IRR.CI.covs,
        `RR M_orig` = IRR.covs.unmatch,
        `RR M_orig CI` = IRR.CI.unmatch,
        `Fisher p-value` = p_value_RR,
        `Adj. Fisher p-value` = adjusted_p_value_RR,
        `Fiducial Interval` = fisher.RR.CI)

RR_tab <- RR_tab %>%
  as.matrix() %>%
  `row.names<-`(cities) %>%
  as.data.frame() %>%
  dplyr::select(-c(city))


# now switch rows and columns
RR_tab <- t(RR_tab) |> as.data.frame()

# export latex table
print(xtable(RR_tab, type = "latex"), file = "RR_tab.tex")

```


